// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLxkeF8jFg5OROifjWujJPQW4_j2yYXVc',
    appId: '1:425609859734:android:834a548a8616c0586e28b7',
    messagingSenderId: '',
    projectId: 'electric-billing-system-4356f',
    authDomain: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxkeF8jFg5OROifjWujJPQW4_j2yYXVc',
    appId: '1:425609859734:android:834a548a8616c0586e28b7',
    messagingSenderId: '606035065133',
    projectId: 'electric-billing-system-4356f',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxkeF8jFg5OROifjWujJPQW4_j2yYXVc',
    appId: '1:425609859734:android:834a548a8616c0586e28b7',
    messagingSenderId: '',
    projectId: 'electric-billing-system-4356f',
    storageBucket: '',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLxkeF8jFg5OROifjWujJPQW4_j2yYXVc',
    appId: '1:425609859734:android:834a548a8616c0586e28b7',
    messagingSenderId: '', 
    projectId: 'electric-billing-system-4356f',
  
  );
}
